files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
    update_option: update_as_unapproved
    languages_mapping:
      two_letters_code:
        zh-CN: zh-rCN
        zh-TW: zh-rTW
        pt-BR: pt-rBR
        es-ES: es
        ru-RU: ru