// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: BloodTestMultiMessage.proto at 11:1
package com.eveningoutpost.dexdrip.messages;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class BloodTestMultiMessage extends Message<BloodTestMultiMessage, BloodTestMultiMessage.Builder> {
  public static final ProtoAdapter<BloodTestMultiMessage> ADAPTER = new ProtoAdapter_BloodTestMultiMessage();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "com.eveningoutpost.dexdrip.messages.BloodTestMessage#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<BloodTestMessage> bloodtest_message;

  public BloodTestMultiMessage(List<BloodTestMessage> bloodtest_message) {
    this(bloodtest_message, ByteString.EMPTY);
  }

  public BloodTestMultiMessage(List<BloodTestMessage> bloodtest_message, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.bloodtest_message = Internal.immutableCopyOf("bloodtest_message", bloodtest_message);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.bloodtest_message = Internal.copyOf("bloodtest_message", bloodtest_message);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof BloodTestMultiMessage)) return false;
    BloodTestMultiMessage o = (BloodTestMultiMessage) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(bloodtest_message, o.bloodtest_message);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (bloodtest_message != null ? bloodtest_message.hashCode() : 1);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (bloodtest_message != null) builder.append(", bloodtest_message=").append(bloodtest_message);
    return builder.replace(0, 2, "BloodTestMultiMessage{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<BloodTestMultiMessage, Builder> {
    public List<BloodTestMessage> bloodtest_message;

    public Builder() {
      bloodtest_message = Internal.newMutableList();
    }

    public Builder bloodtest_message(List<BloodTestMessage> bloodtest_message) {
      Internal.checkElementsNotNull(bloodtest_message);
      this.bloodtest_message = bloodtest_message;
      return this;
    }

    @Override
    public BloodTestMultiMessage build() {
      return new BloodTestMultiMessage(bloodtest_message, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_BloodTestMultiMessage extends ProtoAdapter<BloodTestMultiMessage> {
    ProtoAdapter_BloodTestMultiMessage() {
      super(FieldEncoding.LENGTH_DELIMITED, BloodTestMultiMessage.class);
    }

    @Override
    public int encodedSize(BloodTestMultiMessage value) {
      return BloodTestMessage.ADAPTER.asRepeated().encodedSizeWithTag(1, value.bloodtest_message)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, BloodTestMultiMessage value) throws IOException {
      if (value.bloodtest_message != null) BloodTestMessage.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.bloodtest_message);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public BloodTestMultiMessage decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.bloodtest_message.add(BloodTestMessage.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public BloodTestMultiMessage redact(BloodTestMultiMessage value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.bloodtest_message, BloodTestMessage.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
