name: Unit Test & Build APK (ICR_ISF_profile)

on:
  push:
    branches: [ ICR_ISF_profile ]
  pull_request:
    branches: [ ICR_ISF_profile ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 17 ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: adopt
    - name: Run unit tests and assemble APKs
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assembleProdRelease testProdReleaseUnitTest
    - name: Check Output
      run: bash ./etc/CheckBuild/check-release.sh test
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: xdrip-prod-release
        path: app/build/outputs/apk/prod/release/*.apk
